### ISSUE TITLE
update career!

### ISSUE THREAD

**Issue by swampstream** [DeGatchi/career-log#1]
just snooping around, would like to see how you've grown. just starting myself too.

**Comment by DeGatchi** [comment]
ah, yes! I need to update this one day ahaha

**Comment by DeGatchi** [comment]
made an update just then 📦

**Comment by swampstream** [comment]
Good job. Alot of stuff added. Nice to read what you've been up to. Hope to pick up  MEV soon, so you tips you shared help alot. 

And good to hear you feel ok after picking up some fitness hours. Good move. Screw pills. Unprocessed food, and movement is half the game. I do a little bouldering myself, kinda feels like physical puzzles to solve while working out a bit. First I went once a week for while (3months, single ticket each visit), and then after that went more often once every other day (got a monthly subscription). A tip to you.

Stay in touch. And again thanks for sharing. They say it's probably the best way to democratise MEV... a nice contribution all in all!

**Comment by DeGatchi** [comment]
Of course, fren. I might add some of the tips I received from my journey as they really helped me get into it in a structured way. 

Yep. Gym is a life-saver. I got burnt out from building TheaterDAO's frontend and lost direction. MEV was really that escape tbh. Bouldering sounds interesting :D 

Hopefully, when I get good enough I can make some public repos to help out :)
